#!/bin/bash

# Istio Traffic Splitting Demo (3 versions)
# Deploys 3 versions of an echo service and splits traffic between them via Istio.

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
WORK_DIR="$SCRIPT_DIR"

RUNTIME_DIR="${TMPDIR:-/tmp}/kuberneteslabs-istio-traffic-splitting"
PF_PID_FILE="$RUNTIME_DIR/port-forward.pids"

is_port_listening() {
  local port="$1"
  if command -v lsof >/dev/null 2>&1; then
    lsof -nP -iTCP:"${port}" -sTCP:LISTEN >/dev/null 2>&1
  else
    return 1
  fi
}

start_port_forward() {
  local namespace="$1"
  local svc="$2"
  local local_port="$3"
  local remote_port="$4"
  local log_file="$RUNTIME_DIR/port-forward-${namespace}-${svc}-${local_port}.log"

  if is_port_listening "${local_port}"; then
    echo "Port ${local_port} is already in use; skipping port-forward for ${namespace}/svc/${svc}."
    return 0
  fi

  if command -v nohup >/dev/null 2>&1; then
    nohup kubectl -n "${namespace}" port-forward "svc/${svc}" "${local_port}:${remote_port}" >"${log_file}" 2>&1 &
  else
    kubectl -n "${namespace}" port-forward "svc/${svc}" "${local_port}:${remote_port}" >"${log_file}" 2>&1 &
  fi
  echo $! >>"$PF_PID_FILE"
}

open_url() {
  local url="$1"
  if command -v open >/dev/null 2>&1; then
    open "${url}" >/dev/null 2>&1 || true
  elif command -v xdg-open >/dev/null 2>&1; then
    xdg-open "${url}" >/dev/null 2>&1 || true
  fi
}

echo "========================================"
echo "Istio Demo 02 - Traffic splitting (3 pods)"
echo "========================================"
echo

echo "Checking prerequisites..."
if ! command -v kubectl &>/dev/null; then
  echo "Error: kubectl is not installed or not in PATH"
  exit 1
fi
if ! kubectl cluster-info &>/dev/null; then
  echo "Error: Cannot connect to Kubernetes cluster"
  exit 1
fi
if ! kubectl -n istio-system get svc istio-ingressgateway >/dev/null 2>&1; then
  echo "Error: Istio ingress gateway not found. Install Istio first (Lab01)."
  exit 1
fi
if ! kubectl -n istio-system get svc kiali >/dev/null 2>&1; then
  echo "Warning: Kiali service not found in istio-system (skipping Kiali open)."
fi

echo
echo "Prerequisites check passed."
echo

mkdir -p "$RUNTIME_DIR" >/dev/null 2>&1 || true

echo
echo "Step 00: Keeping runtime as-is (no cleanup)."
echo "(If you already have a port-forward on 8080, this script will not replace it.)"
echo

echo
echo "Step 01: Deploying echo v1/v2/v3 and service..."
kubectl apply -f "$WORK_DIR/manifests/01-app.yaml"

echo
echo "Step 02: Applying Istio routing (Gateway/VirtualService/DestinationRule)..."
kubectl apply -f "$WORK_DIR/manifests/02-istio-routing.yaml"

echo
echo "Step 03: Waiting for deployments to be available..."
kubectl wait --for=condition=available --timeout=180s deployment/echo-v1 -n istio02
kubectl wait --for=condition=available --timeout=180s deployment/echo-v2 -n istio02
kubectl wait --for=condition=available --timeout=180s deployment/echo-v3 -n istio02
kubectl wait --for=condition=available --timeout=180s deployment/traffic-generator -n istio02

echo
echo "========================================"
echo "Starting Port-Forward + Local Curl Loop"
echo "========================================"

touch "$PF_PID_FILE"
start_port_forward istio-system kiali 20001 20001
start_port_forward istio-system istio-ingressgateway 8080 80

sleep 2

echo "Ingress URL: http://localhost:8080/"
open_url "http://localhost:8080/" || true

if kubectl -n istio-system get svc kiali >/dev/null 2>&1; then
  echo "Kiali URL: http://localhost:20001/kiali/"
  open_url "http://localhost:20001/kiali/" || true
  open_url "http://localhost:20001/kiali/console/graph/namespaces?namespaces=istio02" || true
fi

echo
echo "Runtime dir: $RUNTIME_DIR"
echo "Port-forward PIDs: $PF_PID_FILE"
echo "In-cluster traffic is generated by istio02/deployment/traffic-generator"
echo
echo "Stop port-forward: xargs kill < $PF_PID_FILE"
echo "Watch traffic: kubectl logs -n istio02 deployment/traffic-generator -f"
echo
echo "To see traffic splitting in Kiali:"
echo "- Go to Graph"
echo "- Select namespace: istio02"
echo "- Turn on 'Requests distribution' (traffic animation/labels)"
echo "Cleanup resources: kubectl delete -f manifests/02-istio-routing.yaml; kubectl delete -f manifests/01-app.yaml"

echo
echo "========================================"
echo "Streaming traffic-generator logs (Ctrl+C to stop)"
echo "========================================"
kubectl logs -n istio02 deployment/traffic-generator -f
