{
 "title": "Kube-State Overview - Demo",
 "refresh": "15s",
 "panels": [
  {
   "title": "Deployments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(kube_deployment_labels{})"
    }
   ]
  },
  {
   "title": "DaemonSets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "count(kube_daemonset_labels{})" }
   ]
  },
  {
   "title": "StatefulSets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(kube_statefulset_labels{})"
    }
   ]
  }
 ]
}