# Elasticsearch - ArgoCD Application for the EFK stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk-elasticsearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nirgeier/KubernetesLabs
    targetRevision: HEAD
    path: Labs/33-EFK/helm/elasticsearch
    helm:
      releaseName: elasticsearch
  destination:
    server: https://kubernetes.default.svc
    namespace: efk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
