# Filebeat - ArgoCD Application for the EFK stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk-filebeat
  namespace: argocd
  annotations:
    # Deploy after Elasticsearch is Healthy (sync wave 1)
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nirgeier/KubernetesLabs
    targetRevision: HEAD
    path: Labs/33-EFK/helm/filebeat
    helm:
      releaseName: filebeat
  destination:
    server: https://kubernetes.default.svc
    namespace: efk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
