---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: telepresence-demo
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Telepresence Demo</title>
        <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                min-height: 100vh;
                padding: 20px;
            }
            .container { max-width: 1200px; margin: 0 auto; }
            .header {
                background: white;
                padding: 30px;
                border-radius: 10px;
                box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);
                margin-bottom: 30px;
                text-align: center;
            }
            h1 { color: #333; margin-bottom: 10px; }
            .subtitle { color: #666; font-size: 18px; }
            .grid {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
                gap: 20px;
                margin-bottom: 30px;
            }
            .card {
                background: white;
                padding: 25px;
                border-radius: 10px;
                box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);
            }
            .card h2 { color: #667eea; margin-bottom: 15px; font-size: 22px; }
            .status {
                display: inline-block;
                padding: 5px 15px;
                border-radius: 20px;
                font-size: 14px;
                font-weight: bold;
                margin-bottom: 15px;
            }
            .status.healthy { background: #d4edda; color: #155724; }
            .status.error { background: #f8d7da; color: #721c24; }
            .status.loading { background: #fff3cd; color: #856404; }
            button {
                background: #667eea;
                color: white;
                border: none;
                padding: 12px 24px;
                border-radius: 5px;
                cursor: pointer;
                font-size: 16px;
                margin: 5px;
                transition: background 0.3s;
            }
            button:hover { background: #5568d3; }
            .data-item {
                background: #f8f9fa;
                padding: 10px;
                margin: 10px 0;
                border-radius: 5px;
                border-left: 4px solid #667eea;
            }
            .info-badge {
                display: inline-block;
                background: #e3f2fd;
                color: #0277bd;
                padding: 5px 10px;
                border-radius: 3px;
                margin: 5px;
                font-size: 14px;
            }
            .timestamp { color: #999; font-size: 12px; margin-top: 10px; }
            .error-message {
                background: #f8d7da;
                color: #721c24;
                padding: 15px;
                border-radius: 5px;
                margin: 10px 0;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🚀 Telepresence Demo Application</h1>
                <p class="subtitle">Real-time Kubernetes Development Testing</p>
            </div>
            <div class="grid">
                <div class="card">
                    <h2>Backend Service</h2>
                    <span id="backend-status" class="status loading">Checking...</span>
                    <div id="backend-info"></div>
                    <button onclick="checkHealth()">Check Health</button>
                    <button onclick="fetchData()">Fetch Data</button>
                </div>
                <div class="card">
                    <h2>Users</h2>
                    <span id="users-status" class="status loading">Ready</span>
                    <div id="users-info"></div>
                    <button onclick="fetchUsers()">Load Users</button>
                </div>
            </div>
            <div class="card">
                <h2>📊 Service Data</h2>
                <div id="data-container">
                    <p style="color: #999;">Click "Fetch Data" to load metrics</p>
                </div>
            </div>
        </div>
        <script>
            const API = '/api';
            window.onload = () => { checkHealth(); fetchUsers(); };
            async function checkHealth() {
                try {
                    const res = await fetch(`${API}/health`);
                    const data = await res.json();
                    document.getElementById('backend-status').className = 'status healthy';
                    document.getElementById('backend-status').textContent = 'Healthy ✓';
                    document.getElementById('backend-info').innerHTML = `
                        <div class="info-badge">Env: ${data.environment}</div>
                        <div class="timestamp">${new Date(data.timestamp).toLocaleString()}</div>
                    `;
                } catch(e) {
                    document.getElementById('backend-status').className = 'status error';
                    document.getElementById('backend-status').textContent = 'Error ✗';
                }
            }
            async function fetchData() {
                try {
                    const res = await fetch(`${API}/data`);
                    const data = await res.json();
                    const metrics = data.data.data.map(item => `
                        <div class="data-item"><strong>${item.name}:</strong> ${item.value} ${item.unit}</div>
                    `).join('');
                    document.getElementById('data-container').innerHTML = `
                        <h3 style="color: #667eea;">Metrics from Data Service</h3>
                        <div class="info-badge">Source: ${data.source}</div>
                        ${metrics}
                    `;
                } catch(e) {
                    document.getElementById('data-container').innerHTML = 
                        `<div class="error-message">Error: ${e.message}</div>`;
                }
            }
            async function fetchUsers() {
                try {
                    const res = await fetch(`${API}/users`);
                    const data = await res.json();
                    const users = data.users.map(u => `
                        <div class="data-item">
                            <strong>${u.name}</strong><br>
                            ${u.email} - ${u.role}
                        </div>
                    `).join('');
                    document.getElementById('users-info').innerHTML = `
                        <div class="info-badge">Total: ${data.count}</div>
                        ${users}
                    `;
                    document.getElementById('users-status').className = 'status healthy';
                    document.getElementById('users-status').textContent = 'Loaded ✓';
                } catch(e) {
                    document.getElementById('users-info').innerHTML = 
                        `<div class="error-message">Error loading users</div>`;
                }
            }
            setInterval(checkHealth, 30000);
        </script>
    </body>
    </html>
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;
        
        location / {
            try_files $uri $uri/ /index.html;
        }
        
        location /api/ {
            proxy_pass http://backend:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: telepresence-demo
  labels:
    app: frontend
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: nginx:alpine
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: frontend-config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: frontend-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: frontend-config
          configMap:
            name: frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: telepresence-demo
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: LoadBalancer
