apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
  namespace: demo-fluentbit
  labels:
    app: log-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
        - name: log-generator
          image: busybox:1.36
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                echo "{\"app\": \"log-generator\", \"pod\": \"$(hostname)\", \"timestamp_str\": \"$(date)\", \"value\": $((RANDOM % 100)), \"message\": \"structured log sample\"}"
                sleep 1
              done
