# EFK Stack - nested App of Apps managed by the root App of Apps.
# This application watches Labs/33-EFK/argocd-apps/ and manages
# all EFK component applications (Elasticsearch, Filebeat, Kibana, etc.).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nirgeier/KubernetesLabs
    targetRevision: HEAD
    path: Labs/33-EFK/argocd-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
