apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-azureblob
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
      containers:
        - name: fluentd-azureblob
          image: fluent/fluentd-kubernetes-daemonset:v1-debian-azureblob
          imagePullPolicy: Always
          env:
            - name: AZUREBLOB_ACCOUNT_NAME
              value: ""
            # Use AZUREBLOB_ACCOUNT_KEY for access key authorization, AZUREBLOB_SAS_TOKEN for shared access signature authorization,
            # AZUREBLOB_CONNECTION_STRING to use the full connection string generated in the Azure Portal or neither to use Managed Service Identity.
            - name: AZUREBLOB_ACCOUNT_KEY
              value: ""
            - name: AZUREBLOB_CONNECTION_STRING
              value: ""
            - name: AZUREBLOB_SAS_TOKEN
              value: ""
            - name: AZUREBLOB_CONTAINER
              value: ""
            - name: AZUREBLOB_LOG_PATH
              value: ""
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
