apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd:alpine
          ports:
            - containerPort: 80
          command: ["/bin/sh", "-c"]
          args:
            - |
              if ! command -v curl >/dev/null 2>&1; then
                apk add --no-cache curl >/dev/null 2>&1
              fi
              httpd -D FOREGROUND &
              while true; do
                echo "$(date): HTTPD curling nginx" | tee -a /usr/local/apache2/logs/curl.log
                curl -s --max-time 5 http://nginx.demo.svc.cluster.local 2>&1 | tee -a /usr/local/apache2/logs/curl.log
                sleep 3
              done
          volumeMounts:
            - name: log-volume
              mountPath: /usr/local/apache2/logs
      volumes:
        - name: log-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  namespace: demo
spec:
  selector:
    app: httpd
  ports:
    - port: 80
      targetPort: 80
